### ISSUE TITLE
java.lang.ClassCastException: android.graphics.Bitmap cannot be cast to android.graphics.drawable.Drawable

### ISSUE THREAD

**Issue by 1wayticket** [YvesCheung/SVGAGlidePlugin#7]
我们存在业务需要在recyclerview中加载svga，经评估选用了该框架加载svga提高复用效率。
但是会有一定概率出现该异常，异常堆栈如下。
Thread Name: 'pool-20-thread-1'
Back traces starts.
java.lang.ClassCastException: android.graphics.Bitmap cannot be cast to android.graphics.drawable.Drawable
	at com.opensource.svgaplayer.glideplugin.o$a.a(SVGAImageViewTargetFactory.kt:26)
	at com.bumptech.glide.d.a.f.b(ImageViewTarget.java:124)
	at com.bumptech.glide.d.a.f.a(ImageViewTarget.java:101)
	at com.bumptech.glide.d.j.a(SingleRequest.java:639)
	at com.bumptech.glide.d.j.a(SingleRequest.java:578)
	at com.bumptech.glide.load.a.k.a(Engine.java:220)
	at com.bumptech.glide.d.j.a(SingleRequest.java:451)
	at com.bumptech.glide.d.a.k$a.a(ViewTarget.java:376)
	at com.bumptech.glide.d.a.k.a(ViewTarget.java:218)
	at com.bumptech.glide.d.j.a(SingleRequest.java:253)
	at com.bumptech.glide.manager.r.d(RequestTracker.java:115)
	at com.bumptech.glide.k.resumeRequests(RequestManager.java:324)
	at com.bumptech.glide.k.onStart(RequestManager.java:349)
	at com.bumptech.glide.manager.a.a(ActivityFragmentLifecycle.java:51)

麻烦给看下是否是bug？

**Comment by 1wayticket** [comment]
经确认是SVGAImageViewTargetFactory忽略了类型转换,强制把所有的SvgaImageView都强转为SVGADrawableImageViewTarget，导致其余使用SvgaImageview的地方加载静态图且asBitmap的时候类型转换出错。
希望作者有时间优化下这里。
```
 @Suppress("UNCHECKED_CAST")
    override fun <Z : Any> buildTarget(view: ImageView, clazz: Class<Z>): ViewTarget<ImageView, Z> {
        if (view is SVGAImageView) {
            return SVGADrawableImageViewTarget(view) as ViewTarget<ImageView, Z>
        }
        return super.buildTarget(view, clazz)
    }
```

**Comment by YvesCheung** [comment]
今天修

**Comment by YvesCheung** [comment]
fbbd13e8afb99d9fe9e70bf11abacc2f5a3c5a4c
Fix. Release in 4.9.4
